/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author Mario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lresultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tvalor1 = new javax.swing.JTextField();
        tvalor2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Bcalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Rsuma = new javax.swing.JRadioButton();
        Rresta = new javax.swing.JRadioButton();
        Rmulti = new javax.swing.JRadioButton();
        Rdivision = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lresultado.setBackground(new java.awt.Color(255, 255, 255));
        lresultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lresultado.setForeground(new java.awt.Color(153, 0, 0));
        lresultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lresultado.getAccessibleContext().setAccessibleName("lresultado");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 570, 110);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        tvalor1.setBackground(new java.awt.Color(255, 255, 153));
        tvalor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tvalor1.setForeground(java.awt.Color.red);

        tvalor2.setBackground(new java.awt.Color(255, 255, 153));
        tvalor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tvalor2.setForeground(java.awt.Color.red);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("VALOR 2");

        Bcalcular.setBackground(new java.awt.Color(51, 255, 51));
        Bcalcular.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Bcalcular.setForeground(java.awt.Color.red);
        Bcalcular.setText("CALCULAR");
        Bcalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BcalcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BcalcularMouseExited(evt);
            }
        });
        Bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcalcularActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("VALOR 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(tvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(tvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(Bcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(Bcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 120, 570, 330);

        buttonGroup1.add(Rsuma);
        Rsuma.setSelected(true);
        Rsuma.setText("SUMA");
        Rsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RsumaActionPerformed(evt);
            }
        });
        getContentPane().add(Rsuma);
        Rsuma.setBounds(570, 190, 56, 21);

        buttonGroup1.add(Rresta);
        Rresta.setText("RESTA");
        getContentPane().add(Rresta);
        Rresta.setBounds(570, 230, 56, 21);

        buttonGroup1.add(Rmulti);
        Rmulti.setText("MULTIPLICACION");
        getContentPane().add(Rmulti);
        Rmulti.setBounds(570, 270, 120, 21);

        buttonGroup1.add(Rdivision);
        Rdivision.setText("DIVISION");
        getContentPane().add(Rdivision);
        Rdivision.setBounds(570, 310, 71, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcalcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalcularMouseEntered

    }//GEN-LAST:event_BcalcularMouseEntered

    private void BcalcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcalcularMouseExited

    }//GEN-LAST:event_BcalcularMouseExited

    private void BcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcalcularActionPerformed
        float num1 = 0, num2 = 0, total = 0;
        num1 = Float.parseFloat(tvalor1.getText());
        num2 = Float.parseFloat(tvalor2.getText());

        if (Rsuma.isSelected()) {
            total = num1 + num2;
        }
        if (Rresta.isSelected()) {
            total = num1 - num2;
        }
        if (Rmulti.isSelected()) {
            total = num1 * num2;
        }
        if (Rdivision.isSelected()) {
            total = num1 / num2;
        }

        lresultado.setText(String.valueOf(total));

    }//GEN-LAST:event_BcalcularActionPerformed

    private void RsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RsumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RsumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcalcular;
    private javax.swing.JRadioButton Rdivision;
    private javax.swing.JRadioButton Rmulti;
    private javax.swing.JRadioButton Rresta;
    private javax.swing.JRadioButton Rsuma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lresultado;
    private javax.swing.JTextField tvalor1;
    private javax.swing.JTextField tvalor2;
    // End of variables declaration//GEN-END:variables
}
